apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 9.3.2
    helm:
      valueFiles:
      - values.yaml
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
